// <auto-generated />
using System;
using System.Collections.Generic;
using Fullerene.Manager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fullerene.Manager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.AndroidAppPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AndroidApplicationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("boolean");

                    b.Property<string>("NixPackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NixPackageRepoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NixPackageRepoId", "NixPackageName", "AndroidApplicationId")
                        .IsUnique();

                    b.ToTable("AndroidAppPackages");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.AndroidAppPackageVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AndroidApplicationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppLicense")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppLogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AppVersionReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppVersionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BaseVersionCode")
                        .HasColumnType("integer");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NixDerivationHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NixPackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NixPackageRepoId")
                        .HasColumnType("uuid");

                    b.Property<int>("NixPackageRevision")
                        .HasColumnType("integer");

                    b.Property<int>("ReleaseChannel")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseNotes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AppName"), "gist");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("AppName"), new[] { "gist_trgm_ops" });

                    b.HasIndex("NixPackageRepoId", "CommitHash");

                    b.HasIndex("NixPackageRepoId", "NixPackageName", "AndroidApplicationId");

                    b.ToTable("AndroidAppPackageVersions");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactDataRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("boolean");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FileData", "Fullerene.Manager.Domain.Models.Artifact.FileData#StorageFileData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FileSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<long>("FileSizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("FileStorageKey")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "IdSigFileData", "Fullerene.Manager.Domain.Models.Artifact.IdSigFileData#StorageFileData", b1 =>
                        {
                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FileSha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<long>("FileSizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("FileStorageKey")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ArtifactDataRecordId");

                    b.HasIndex("BuildWorkflowId");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.ArtifactDataRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArtifactType")
                        .HasColumnType("integer");

                    b.Property<int>("MinApiLevel")
                        .HasColumnType("integer");

                    b.Property<int>("TargetApiLevel")
                        .HasColumnType("integer");

                    b.Property<int>("VersionCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ArtifactDataRecords");

                    b.HasDiscriminator<int>("ArtifactType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.BuildWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AndroidAppPackageVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AndroidAppPackageVersionId");

                    b.ToTable("BuildWorkflows");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.NixPackageRepo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GitRepositoryUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gist");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gist_trgm_ops" });

                    b.ToTable("NixPackageRepos");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.NixRepoCommit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CommitDateTimeOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NixRepoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("NixRepoCommits");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.WorkflowEvents.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateTimeOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BuildWorkflowId");

                    b.ToTable("WorkflowEvents");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.ArtifactSplitDataRecord", b =>
                {
                    b.HasBaseType("Fullerene.Manager.Domain.Models.ArtifactDataRecord");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SplitId")
                        .IsRequired()
                        .HasColumnType("text");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.ConcreteArtifactDataRecords.StandaloneSingleAbiArtifactDataRecord", b =>
                {
                    b.HasBaseType("Fullerene.Manager.Domain.Models.ArtifactDataRecord");

                    b.Property<int>("CpuArchitecture")
                        .HasColumnType("integer");

                    b.ToTable("ArtifactDataRecords", t =>
                        {
                            t.Property("CpuArchitecture")
                                .HasColumnName("StandaloneSingleAbiArtifactDataRecord_CpuArchitecture");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.ConcreteArtifactDataRecords.StandaloneUniversalArtifactDataRecord", b =>
                {
                    b.HasBaseType("Fullerene.Manager.Domain.Models.ArtifactDataRecord");

                    b.Property<int[]>("CpuArchitectures")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.ConcreteArtifactDataRecords.AbiArtifactSplitDataRecord", b =>
                {
                    b.HasBaseType("Fullerene.Manager.Domain.Models.ArtifactSplitDataRecord");

                    b.Property<int>("CpuArchitecture")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.ConcreteArtifactDataRecords.AssetsArtifactSplitDataRecord", b =>
                {
                    b.HasBaseType("Fullerene.Manager.Domain.Models.ArtifactSplitDataRecord");

                    b.Property<int>("AssetModuleType")
                        .HasColumnType("integer");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageTargeting")
                        .HasColumnType("text");

                    b.Property<int?>("TextureCompressionFormat")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.ConcreteArtifactDataRecords.DensityArtifactSplitDataRecord", b =>
                {
                    b.HasBaseType("Fullerene.Manager.Domain.Models.ArtifactSplitDataRecord");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Density", "Fullerene.Manager.Domain.Models.ConcreteArtifactDataRecords.DensityArtifactSplitDataRecord.Density#ScreenDensity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("Alias")
                                .HasColumnType("integer");

                            b1.Property<int?>("Dpi")
                                .HasColumnType("integer");
                        });

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.ConcreteArtifactDataRecords.LanguageArtifactSplitDataRecord", b =>
                {
                    b.HasBaseType("Fullerene.Manager.Domain.Models.ArtifactSplitDataRecord");

                    b.Property<string>("LanguageTargeting")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("ArtifactDataRecords", t =>
                        {
                            t.Property("LanguageTargeting")
                                .HasColumnName("LanguageArtifactSplitDataRecord_LanguageTargeting");
                        });

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.MasterArtifactSplitDataRecord", b =>
                {
                    b.HasBaseType("Fullerene.Manager.Domain.Models.ArtifactSplitDataRecord");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.ConcreteArtifactDataRecords.BaseArtifactSplitDataRecord", b =>
                {
                    b.HasBaseType("Fullerene.Manager.Domain.Models.MasterArtifactSplitDataRecord");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.ConcreteArtifactDataRecords.FeatureArtifactSplitDataRecord", b =>
                {
                    b.HasBaseType("Fullerene.Manager.Domain.Models.MasterArtifactSplitDataRecord");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.AndroidAppPackage", b =>
                {
                    b.HasOne("Fullerene.Manager.Domain.Models.NixPackageRepo", "NixRepo")
                        .WithMany("AndroidApps")
                        .HasForeignKey("NixPackageRepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NixRepo");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.AndroidAppPackageVersion", b =>
                {
                    b.HasOne("Fullerene.Manager.Domain.Models.NixPackageRepo", "NixPackageRepo")
                        .WithMany()
                        .HasForeignKey("NixPackageRepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fullerene.Manager.Domain.Models.NixRepoCommit", "NixRepoCommit")
                        .WithMany("AndroidAppPackageVersions")
                        .HasForeignKey("NixPackageRepoId", "CommitHash")
                        .HasPrincipalKey("NixRepoId", "CommitHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fullerene.Manager.Domain.Models.AndroidAppPackage", "AndroidAppPackage")
                        .WithMany("AndroidAppPackageVersions")
                        .HasForeignKey("NixPackageRepoId", "NixPackageName", "AndroidApplicationId")
                        .HasPrincipalKey("NixPackageRepoId", "NixPackageName", "AndroidApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AndroidAppPackage");

                    b.Navigation("NixPackageRepo");

                    b.Navigation("NixRepoCommit");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.Artifact", b =>
                {
                    b.HasOne("Fullerene.Manager.Domain.Models.ArtifactDataRecord", "ArtifactDataRecord")
                        .WithMany("Artifacts")
                        .HasForeignKey("ArtifactDataRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fullerene.Manager.Domain.Models.BuildWorkflow", "BuildWorkflow")
                        .WithMany("Artifacts")
                        .HasForeignKey("BuildWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtifactDataRecord");

                    b.Navigation("BuildWorkflow");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.BuildWorkflow", b =>
                {
                    b.HasOne("Fullerene.Manager.Domain.Models.AndroidAppPackageVersion", "AndroidAppPackageVersion")
                        .WithMany("BuildWorkflows")
                        .HasForeignKey("AndroidAppPackageVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AndroidAppPackageVersion");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.NixRepoCommit", b =>
                {
                    b.HasOne("Fullerene.Manager.Domain.Models.NixPackageRepo", "NixRepo")
                        .WithMany("NixRepoCommits")
                        .HasForeignKey("NixRepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NixRepo");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.WorkflowEvents.WorkflowEvent", b =>
                {
                    b.HasOne("Fullerene.Manager.Domain.Models.BuildWorkflow", "BuildWorkflow")
                        .WithMany("WorkflowEvents")
                        .HasForeignKey("BuildWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildWorkflow");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.AndroidAppPackage", b =>
                {
                    b.Navigation("AndroidAppPackageVersions");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.AndroidAppPackageVersion", b =>
                {
                    b.Navigation("BuildWorkflows");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.ArtifactDataRecord", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.BuildWorkflow", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("WorkflowEvents");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.NixPackageRepo", b =>
                {
                    b.Navigation("AndroidApps");

                    b.Navigation("NixRepoCommits");
                });

            modelBuilder.Entity("Fullerene.Manager.Domain.Models.NixRepoCommit", b =>
                {
                    b.Navigation("AndroidAppPackageVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
