services:
  rabbitmq:
    container_name: fullerene-rabbitmq
    image: docker.io/rabbitmq:4.3.1-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 5672 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  garage:
    container_name: fullerene-garage
    build:
      context: ./services/Garage
    env_file:
      - .env.garage
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - garage_meta:/var/lib/garage/meta:z
      - garage_data:/var/lib/garage/data:z
    healthcheck:
      test: ["CMD", "/garage", "status"]
      interval: 5s
      timeout: 5s
      retries: 10

  db:
    container_name: fullerene-postgres
    image: docker.io/postgres:18.4-alpine3.23
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fullerene"]
      interval: 5s
      timeout: 5s
      retries: 10

  manager:
    container_name: fullerene-manager
    build:
      context: .
      dockerfile: services/Fullerene.Manager/src/Fullerene.Manager.Api/DockerfileFast
    ports:
      - "5130:8080"
    env_file:
      - .env.manager
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      garage:
        condition: service_healthy

  worker:
    container_name: fullerene-worker
    build:
      context: .
      dockerfile: services/Fullerene.Worker/src/Fullerene.Worker.App/DockerfileFast
    volumes:
      - /run/user/1000/podman/podman.sock:/run/podman/podman.sock
    env_file:
      - .env.worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      garage:
        condition: service_healthy

  signer:
    container_name: fullerene-signer
    build:
      context: .
      dockerfile: services/Fullerene.Signer/src/Fullerene.Signer.App/DockerfileFast
    tmpfs:
      - /run/secrets_ramdisk:size=32m,mode=0700
    env_file:
      - .env.signer
    depends_on:
      rabbitmq:
        condition: service_healthy
      garage:
        condition: service_healthy

volumes:
  nix_build_cache:
    name: nix_build_cache
  rabbitmq_data:
  rabbitmq_log:
  garage_meta:
  garage_data:
  postgres_data:
