<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\shared\Fullerene.Shared.Infrastructure\Fullerene.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\Fullerene.Signer.Application\Fullerene.Signer.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.10.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
  </ItemGroup>

</Project>
